# Site settings
baseurl = "https://jogi.blog/"
themesDir = "themes"
languageCode = "en-us"
title = "Vashishtha Jogi"
theme = "alfred"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""
pygmentsUseClasses=true

[params]
	name = "Vashishtha Jogi"
	description = ""
	bio = "engineer. photographer."
	# Enter optionally your twitter account
	twitter = "VashishthaJogi"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = "subscribe"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm an blogger."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/VashishthaJogi"
    github   = "https://www.github.com/jvashishtha"

[outputFormats]
	[outputFormats.json]
		mediaType = "application/json"
		baseName = "index"
		isPlainText = true

[outputs]
	home = ["HTML", "JSON", "RSS"]
	page = ["HTML"]
