# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Vashishtha Jogi"
enableRobotsTXT = true
disableAliases = true
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-4839600-11"
pygmentsUseClasses=true
pygmentsCodeFences=true
paginate = 10

[params]
name = "Vashishtha Jogi"
description = ""
bio = "thoughts about programming and photography"
# Enter optionally your twitter account
twitter = "VashishthaJogi"
enableRSS = true

# Integrate Javascript files or stylesheets by adding the url to the external assets or by
# linking local files with their path relative to the static folder, e.g. "css/styles.css"
customCSS = []
customJS  = []

# The variables below are optionally too and can be used to
# translate or customize each string of the theme.

# Navigation links
home = ""
subscribe = "subscribe"
# Pagination links
olderPosts = ""
newerPosts = ""
readMore = ""
copyright = ""
# Sharing options and author information in posts
aboutAuthor = "I'm an blogger."
tweet = ""
share = ""
# 404 page
title404 = ""
subtitle404 = ""
disallow_search_engines = false # set robots.txt to disallow everything

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/VashishthaJogi"
    github   = "https://www.github.com/jvashishtha"

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "JSON", "REDIRECTS", "HEADERS"]
page = ["HTML"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
	[outputFormats.json]
		mediaType = "application/json"
		baseName = "index"
		isPlainText = true
    # add output format for netlify _redirects
    [outputFormats.REDIRECTS]
        mediatype = "text/netlify"
        baseName = "_redirects"
        isPlainText = true
        notAlternative = true
    # add output format for netlify _headers
    [outputFormats.HEADERS]
        mediatype = "text/netlify"
        baseName = "_headers"
        isPlainText = true
        notAlternative = true
